spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?connectionTimeZone=Asia/Seoul&forceConnectionTimeZoneToSession=true&characterEncoding=UTF-8&sslMode=REQUIRED
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: info
    com.buzz.fortyall_desk: debug
